### ISSUE TITLE
Practica 3_ RA con objetos 3D en Heroku

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo-nancy-brenda-belem#2]
[Practica 3_Objetos en 3D en Heroku.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo-nancy-brenda-belem/files/8301894/Practica.3_Objetos.en.3D.en.Heroku.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20 puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
